apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "external-targets.fullname" . }}-configmap
  labels:
    {{- include "external-targets.labels" . | nindent 4 }}
data:
  BASE_ENDPOINT_MANIFEST: |
    apiVersion: v1
    kind: Endpoints
    metadata:
      name: {{ include "external-targets.fullname" . }}
      namespace: {{ .Release.Namespace }}
    labels:
      {{- include "external-targets.labels" . | nindent 6 }}
    subsets:
      - addresses: []
        ports:
          - name: metrics
            port: {{ .Values.service.metricsPort }}
            protocol: TCP
  TARGETS: |
    {{- range .Values.externalTargets }}
    {{ . }}
    {{- end }}
